# Generated by Django 3.1.1 on 2021-09-18 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videogroup',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_group', to='store.store', verbose_name='店铺'),
        ),
        migrations.AddField(
            model_name='video',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_video', to='store.store', verbose_name='店铺'),
        ),
        migrations.AddField(
            model_name='imagegroup',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_group', to='store.store', verbose_name='店铺'),
        ),
        migrations.AddField(
            model_name='image',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_image', to='store.store', verbose_name='店铺'),
        ),
        migrations.AddField(
            model_name='author',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_author', to='store.store', verbose_name='店铺'),
        ),
        migrations.AddField(
            model_name='articlegroup',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_group', to='store.store', verbose_name='店铺'),
        ),
        migrations.AddField(
            model_name='article',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_article', to='store.store', verbose_name='店铺'),
        ),
    ]
