# Generated by Django 3.1.1 on 2022-06-05 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(max_length=50, null=True, unique=True)),
                ('pid', models.CharField(max_length=50, unique=True, verbose_name='用户编号')),
                ('likes', models.JSONField(null=True, verbose_name='收藏')),
                ('reviewLikes', models.JSONField(default=list, verbose_name='评论点赞')),
                ('addressList', models.JSONField(default=list, verbose_name='收货地址')),
                ('cart', models.JSONField(default=list, verbose_name='购物车')),
                ('gender', models.CharField(max_length=5, null=True, verbose_name='性别')),
                ('city', models.CharField(max_length=20, null=True, verbose_name='城市')),
                ('country', models.CharField(max_length=20, null=True, verbose_name='国家')),
                ('province', models.CharField(max_length=20, null=True, verbose_name='省份')),
                ('nickName', models.CharField(max_length=20, null=True, verbose_name='昵称')),
                ('phone', models.CharField(max_length=20, null=True, verbose_name='手机')),
                ('birthDay', models.CharField(default='未设置', max_length=15, null=True, verbose_name='出生年月')),
                ('avatarUrl', models.CharField(max_length=255, verbose_name='用户头像')),
                ('channel', models.CharField(default='微信', max_length=10, verbose_name='渠道')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': 'tb_customer',
                'verbose_name_plural': 'tb_customer',
                'db_table': 'tb_customer',
            },
        ),
    ]
