# Generated by Django 3.1.1 on 2022-02-01 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='channel',
            field=models.CharField(default='微信', max_length=10, verbose_name='渠道'),
        ),
        migrations.AddField(
            model_name='customer',
            name='openid',
            field=models.CharField(max_length=20, null=True, unique=True, verbose_name='用户编号'),
        ),
    ]
