# Generated by Django 3.1.1 on 2022-02-06 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20220201_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='nickName',
            field=models.CharField(max_length=20, null=True, verbose_name='昵称'),
        ),
        migrations.AddField(
            model_name='customer',
            name='sex',
            field=models.CharField(max_length=5, null=True, verbose_name='性别'),
        ),
    ]
