# Generated by Django 3.1.1 on 2022-02-06 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20220206_1252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='star',
        ),
    ]
