# Generated by Django 3.1.1 on 2022-02-06 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_remove_customer_star'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='openid',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='用户编号'),
        ),
    ]
