# Generated by Django 3.1.1 on 2022-02-06 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_auto_20220206_2100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='avatar',
            new_name='avatarUrl',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='sex',
            new_name='gender',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='name',
        ),
        migrations.AddField(
            model_name='customer',
            name='city',
            field=models.CharField(max_length=20, null=True, verbose_name='城市'),
        ),
        migrations.AddField(
            model_name='customer',
            name='country',
            field=models.CharField(max_length=20, null=True, verbose_name='国家'),
        ),
        migrations.AddField(
            model_name='customer',
            name='province',
            field=models.CharField(max_length=20, null=True, verbose_name='省份'),
        ),
    ]
