# Generated by Django 3.1.1 on 2022-02-09 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_auto_20220207_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='birthDay',
            field=models.CharField(default='未设置', max_length=15, null=True, verbose_name='出生年月'),
        ),
    ]
