# Generated by Django 3.1.1 on 2022-02-12 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_auto_20220211_2327'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='nickname',
            new_name='nickName',
        ),
    ]
