# Generated by Django 3.1.1 on 2022-02-14 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0011_auto_20220213_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.JSONField(default=list, null=True, verbose_name='收货地址'),
        ),
    ]
