# Generated by Django 3.1.1 on 2022-02-15 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0012_auto_20220214_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='pid',
            field=models.CharField(default='', max_length=50, unique=True, verbose_name='用户编号'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='openid',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
