# Generated by Django 3.1.1 on 2022-03-02 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0013_auto_20220215_1007'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='address',
            new_name='addressList',
        ),
        migrations.AddField(
            model_name='customer',
            name='defaultAddress',
            field=models.JSONField(null=True, verbose_name='默认地址'),
        ),
    ]
