# Generated by Django 3.1.1 on 2022-03-02 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0014_auto_20220302_1938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='defaultAddress',
        ),
    ]
