# Generated by Django 3.1.1 on 2021-09-22 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0004_auto_20210921_2311'),
    ]

    operations = [
        migrations.CreateModel(
            name='baseData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pv', models.IntegerField(verbose_name='浏览量')),
                ('uv', models.IntegerField(verbose_name='访问量')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='general_data', to='store.store', verbose_name='店铺')),
            ],
            options={
                'verbose_name': '数据概况',
                'verbose_name_plural': '数据概况',
                'db_table': 'tb_baseData',
            },
        ),
    ]
