# Generated by Django 3.1.1 on 2021-09-18 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='分类')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subs', to='industry.industry', verbose_name='行业')),
            ],
            options={
                'verbose_name': '行业',
                'verbose_name_plural': '行业',
                'db_table': 'tb_industry',
            },
        ),
    ]
