# Generated by Django 3.1.1 on 2022-06-05 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(max_length=20, null=True, unique=True, verbose_name='快递单号')),
                ('mailing_method', models.CharField(default='免邮', max_length=10, verbose_name='邮寄方式')),
                ('message', models.JSONField(null=True, verbose_name='快递信息')),
                ('delivery_time', models.DateTimeField(auto_now_add=True, verbose_name='发货时间')),
                ('receiving_time', models.DateTimeField(verbose_name='收货时间')),
                ('orderNum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order', to_field='orderNum', verbose_name='订单号')),
            ],
            options={
                'verbose_name': 'tb_shipment',
                'verbose_name_plural': 'tb_shipment',
                'db_table': 'tb_shipment',
            },
        ),
    ]
