# Generated by Django 3.1.1 on 2022-06-05 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=20, null=True, verbose_name='商品sku')),
                ('title', models.CharField(max_length=100, verbose_name='商品名称')),
                ('slogan', models.CharField(max_length=150, null=True, verbose_name='标语')),
                ('goodsType', models.CharField(max_length=5, verbose_name='商品类型')),
                ('sellModelType', models.CharField(max_length=5, verbose_name='销售类型')),
                ('category', models.JSONField(null=True, verbose_name='商品类别')),
                ('price', models.CharField(max_length=10, verbose_name='价格')),
                ('costPrice', models.CharField(max_length=10, null=True, verbose_name='成本价')),
                ('salesNum', models.IntegerField(default=0, verbose_name='销量')),
                ('sortNum', models.IntegerField(default=0, verbose_name='权重')),
                ('originalPrice', models.CharField(max_length=10, null=True, verbose_name='原价')),
                ('stock', models.IntegerField(default=100, verbose_name='库存')),
                ('isPutAway', models.BooleanField(default=True, verbose_name='是否上架')),
                ('sellUnit', models.CharField(max_length=5, null=True, verbose_name='单位')),
                ('videoUrl', models.CharField(max_length=250, null=True, verbose_name='视频封面')),
                ('videoImage', models.CharField(max_length=250, null=True, verbose_name='视频链接')),
                ('playTime', models.CharField(max_length=10, verbose_name='播放时长')),
                ('goodsImageUrls', models.JSONField(null=True, verbose_name='商品图片')),
                ('goodsCertificateUrls', models.JSONField(default=list, null=True, verbose_name='商品资质')),
                ('defaultImageUrl', models.CharField(max_length=250, null=True, verbose_name='商品图片')),
                ('detail', models.TextField(null=True, verbose_name='商品详情')),
                ('goodsLimitVo', models.JSONField(null=True, verbose_name='限量')),
                ('selectedTag', models.JSONField(null=True, verbose_name='商品标签')),
                ('selectedClassifyList', models.JSONField(default=list, null=True, verbose_name='商品分组')),
                ('selectedGoodsAttrList', models.JSONField(null=True, verbose_name='商品属性')),
                ('selectedGoodsPropList', models.JSONField(null=True, verbose_name='商品参数')),
                ('selectedGoodsRightsList', models.JSONField(default=list, null=True, verbose_name='商品服务')),
                ('putAwayDate', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
                'db_table': 'tb_goods',
                'ordering': ['-sortNum', '-salesNum'],
            },
        ),
        migrations.CreateModel(
            name='GoodsGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.JSONField(verbose_name='商品分组')),
                ('system_group', models.BooleanField(default=True, verbose_name='系统分组')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '商品分组',
                'verbose_name_plural': '商品分组',
                'db_table': 'tb_goods_group',
            },
        ),
        migrations.CreateModel(
            name='GoodsProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property', models.JSONField(verbose_name='商品属性')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '商品属性',
                'verbose_name_plural': '商品属性',
                'db_table': 'tb_goods_property',
            },
        ),
        migrations.CreateModel(
            name='GoodsReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star', models.IntegerField(default=5, verbose_name='星数')),
                ('likes', models.IntegerField(default=0, verbose_name='点赞量')),
                ('children', models.JSONField(default=list, null=True, verbose_name='子评论')),
                ('name', models.CharField(max_length=50, verbose_name='用户名')),
                ('msg', models.CharField(max_length=250, verbose_name='评论')),
                ('specs', models.CharField(max_length=200, verbose_name='规格')),
                ('avatar', models.CharField(max_length=250, verbose_name='用户头像')),
                ('imgs', models.JSONField(default=list, verbose_name='评论图片')),
                ('additional', models.JSONField(null=True, verbose_name='追加评论')),
                ('videoUrl', models.CharField(max_length=100, null=True, verbose_name='视频封面')),
                ('videoImage', models.CharField(max_length=100, null=True, verbose_name='视频链接')),
                ('anonymous', models.BooleanField(default=False, verbose_name='匿名的')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': 'tb_goods_review',
                'verbose_name_plural': 'tb_goods_review',
                'db_table': 'tb_goods_review',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='GoodsTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', models.JSONField(verbose_name='商品标签')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '商品标签',
                'verbose_name_plural': '商品标签',
                'db_table': 'tb_goods_tags',
            },
        ),
        migrations.CreateModel(
            name='SPU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spu', models.CharField(max_length=50, verbose_name='spu编码')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'spu',
                'verbose_name_plural': 'spu',
                'db_table': 'tb_spu',
            },
        ),
    ]
