# Generated by Django 3.1.1 on 2021-12-23 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0010_auto_20211223_1848'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='商品名称')),
                ('slogan', models.CharField(max_length=50, null=True, verbose_name='标语')),
                ('sellModelType', models.CharField(max_length=5, verbose_name='商品类型')),
                ('price', models.CharField(max_length=10, verbose_name='价格')),
                ('costPrice', models.CharField(max_length=10, null=True, verbose_name='成本价')),
                ('initialSales', models.IntegerField(null=True, verbose_name='标语')),
                ('originalPrice', models.CharField(max_length=10, null=True, verbose_name='原价')),
                ('stock', models.IntegerField(default=100, verbose_name='库存')),
                ('sellUnit', models.CharField(max_length=5, null=True, verbose_name='单位')),
                ('videoUrl', models.CharField(max_length=100, null=True, verbose_name='视频封面')),
                ('videoImage', models.CharField(max_length=100, null=True, verbose_name='视频链接')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_goods', to='store.store', verbose_name='商品')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
                'db_table': 'tb_goods',
            },
        ),
    ]
