# Generated by Django 3.1.1 on 2021-12-23 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='goodsType',
            field=models.CharField(default='', max_length=5, verbose_name='商品类型'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='goods',
            name='sellModelType',
            field=models.CharField(max_length=5, verbose_name='销售类型'),
        ),
    ]
