# Generated by Django 3.1.1 on 2021-12-23 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20211223_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='goodsImageUrls',
            field=models.JSONField(null=True, verbose_name='商品图片'),
        ),
        migrations.AddField(
            model_name='goods',
            name='goodsLimitVo',
            field=models.JSONField(null=True, verbose_name='限量'),
        ),
        migrations.AddField(
            model_name='goods',
            name='selectedClassifyList',
            field=models.JSONField(null=True, verbose_name='商品分组'),
        ),
        migrations.AddField(
            model_name='goods',
            name='selectedGoodsAttrList',
            field=models.JSONField(null=True, verbose_name='商品属性'),
        ),
        migrations.AddField(
            model_name='goods',
            name='selectedGoodsPropList',
            field=models.JSONField(null=True, verbose_name='商品参数'),
        ),
        migrations.AddField(
            model_name='goods',
            name='selectedGoodsRightsList',
            field=models.JSONField(null=True, verbose_name='商品服务'),
        ),
    ]
