# Generated by Django 3.1.1 on 2021-12-23 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_auto_20211223_1900'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goods',
            old_name='create_time',
            new_name='putAwayDate',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='initialSales',
        ),
        migrations.AddField(
            model_name='goods',
            name='defaultImageUrl',
            field=models.CharField(max_length=100, null=True, verbose_name='商品图片'),
        ),
        migrations.AddField(
            model_name='goods',
            name='isPutAway',
            field=models.BooleanField(default=True, verbose_name='是否上架'),
        ),
        migrations.AddField(
            model_name='goods',
            name='salesNum',
            field=models.IntegerField(null=True, verbose_name='销量'),
        ),
        migrations.AddField(
            model_name='goods',
            name='sortNum',
            field=models.IntegerField(null=True, verbose_name='权重'),
        ),
    ]
