# Generated by Django 3.1.1 on 2021-12-24 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_auto_20211223_2305'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goods',
            options={'ordering': ['-sortNum'], 'verbose_name': '商品', 'verbose_name_plural': '商品'},
        ),
        migrations.AddField(
            model_name='goods',
            name='category',
            field=models.JSONField(null=True, verbose_name='商品类别'),
        ),
        migrations.AddField(
            model_name='goods',
            name='goodsCertificateUrls',
            field=models.JSONField(null=True, verbose_name='商品资质'),
        ),
        migrations.AddField(
            model_name='goods',
            name='selectedTag',
            field=models.JSONField(null=True, verbose_name='商品标签'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='salesNum',
            field=models.IntegerField(default=0, verbose_name='销量'),
        ),
    ]
