# Generated by Django 3.1.1 on 2021-12-25 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_auto_20211223_1848'),
        ('goods', '0005_auto_20211224_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='sortNum',
            field=models.IntegerField(default=0, verbose_name='权重'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_goods', to='store.store', verbose_name='店铺'),
        ),
        migrations.CreateModel(
            name='GoodsTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', models.JSONField(verbose_name='商品标签')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods_tag', to='store.store', verbose_name='店铺')),
            ],
            options={
                'verbose_name': '商品标签',
                'verbose_name_plural': '商品标签',
                'db_table': 'tb_goods_tags',
            },
        ),
        migrations.CreateModel(
            name='GoodsReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50, verbose_name='用户')),
                ('profile', models.CharField(max_length=100, verbose_name='头像')),
                ('rank', models.IntegerField(default=5, verbose_name='评价等级')),
                ('links', models.IntegerField(default=0, verbose_name='点赞数')),
                ('reply', models.JSONField(null=True, verbose_name='回复')),
                ('videoUrl', models.CharField(max_length=100, null=True, verbose_name='视频封面')),
                ('videoImage', models.CharField(max_length=100, null=True, verbose_name='视频链接')),
                ('defaultImageUrl', models.CharField(max_length=100, null=True, verbose_name='商品图片')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_reviews', to='goods.goods', verbose_name='店铺')),
            ],
            options={
                'verbose_name': '商品评论',
                'verbose_name_plural': '商品评论',
                'db_table': 'tb_goods_reviews',
            },
        ),
        migrations.CreateModel(
            name='GoodsProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', models.JSONField(verbose_name='商品属性')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods_property', to='store.store', verbose_name='店铺')),
            ],
            options={
                'verbose_name': '商品属性',
                'verbose_name_plural': '商品属性',
                'db_table': 'tb_goods_property',
            },
        ),
        migrations.CreateModel(
            name='GoodsGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.JSONField(verbose_name='商品分组')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods_group', to='store.store', verbose_name='店铺')),
            ],
            options={
                'verbose_name': '商品分组',
                'verbose_name_plural': '商品分组',
                'db_table': 'tb_goods_group',
            },
        ),
    ]
