# Generated by Django 3.1.1 on 2021-12-25 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0006_auto_20211225_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsgroup',
            name='system_group',
            field=models.BooleanField(default=True, verbose_name='系统分组'),
        ),
    ]
