# Generated by Django 3.1.1 on 2021-12-26 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0007_goodsgroup_system_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goodsproperty',
            old_name='tags',
            new_name='property',
        ),
        migrations.RenameField(
            model_name='goodsreview',
            old_name='links',
            new_name='like',
        ),
        migrations.RemoveField(
            model_name='goodsreview',
            name='defaultImageUrl',
        ),
        migrations.AddField(
            model_name='goodsreview',
            name='imageUrls',
            field=models.JSONField(null=True, verbose_name='图片'),
        ),
        migrations.AddField(
            model_name='goodsreview',
            name='review',
            field=models.CharField(max_length=250, null=True, verbose_name='回复内容'),
        ),
    ]
