# Generated by Django 3.1.1 on 2021-12-30 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0008_auto_20211226_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='detail',
            field=models.TextField(null=True, verbose_name='商品详情'),
        ),
        migrations.AddField(
            model_name='goods',
            name='spu',
            field=models.CharField(max_length=50, null=True, verbose_name='spu'),
        ),
    ]
