# Generated by Django 3.1.1 on 2022-01-09 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_auto_20211223_1848'),
        ('goods', '0011_auto_20220109_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='sku',
            field=models.CharField(max_length=20, null=True, verbose_name='商品sku'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='spu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='all_skus', to='store.store', verbose_name='店铺'),
        ),
    ]
