# Generated by Django 3.1.1 on 2022-01-10 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0012_auto_20220109_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='spu',
            name='spuCode',
            field=models.CharField(default=1, max_length=50, verbose_name='spu编码'),
            preserve_default=False,
        ),
    ]
