# Generated by Django 3.1.1 on 2022-01-10 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0013_spu_spucode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spu',
            old_name='spuCode',
            new_name='spu',
        ),
        migrations.AlterField(
            model_name='goods',
            name='spu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='all_skus', to='goods.spu', verbose_name='店铺'),
        ),
        migrations.AlterField(
            model_name='spu',
            name='reviews',
            field=models.IntegerField(default=0, verbose_name='评论数'),
        ),
        migrations.AlterField(
            model_name='spu',
            name='sales',
            field=models.IntegerField(default=0, verbose_name='销量'),
        ),
    ]
