# Generated by Django 3.1.1 on 2022-01-12 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0016_auto_20220111_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='anonymous',
            field=models.BooleanField(default=1, verbose_name='匿名的'),
            preserve_default=False,
        ),
    ]
