# Generated by Django 3.1.1 on 2022-01-13 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0019_auto_20220112_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsreview',
            name='specs',
            field=models.CharField(default='', max_length=200, verbose_name='规格'),
            preserve_default=False,
        ),
    ]
