# Generated by Django 3.1.1 on 2022-01-15 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0020_goodsreview_specs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goodsreview',
            name='update_time',
        ),
    ]
