# Generated by Django 3.1.1 on 2022-03-01 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_order_addedreview'),
        ('customer', '0013_auto_20220215_1007'),
        ('goods', '0021_remove_goodsreview_update_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsreview',
            name='customer',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='customer.customer', to_field='openid'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='goodsreview',
            name='orderNum',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='orders.order', to_field='orderNum'),
            preserve_default=False,
        ),
    ]
