# Generated by Django 3.1.1 on 2022-03-06 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0022_auto_20220301_1843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goodsreview',
            name='orderNum',
        ),
        migrations.AlterField(
            model_name='goodsreview',
            name='avatar',
            field=models.CharField(max_length=250, verbose_name='用户头像'),
        ),
    ]
