# Generated by Django 3.1.1 on 2022-03-06 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_auto_20220305_1919'),
        ('goods', '0023_auto_20220306_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsreview',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.order', to_field='orderNum'),
        ),
    ]
