# Generated by Django 3.1.1 on 2022-03-07 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0024_goodsreview_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsreview',
            name='anonymous',
            field=models.BooleanField(default=False, verbose_name='匿名的'),
        ),
        migrations.AlterField(
            model_name='goodsreview',
            name='children',
            field=models.JSONField(default=list, null=True, verbose_name='子评论'),
        ),
    ]
