# Generated by Django 3.1.1 on 2022-06-05 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderNum', models.CharField(max_length=50, unique=True, verbose_name='订单编号')),
                ('status', models.CharField(max_length=10, verbose_name='订单状态')),
                ('note', models.CharField(max_length=250, null=True, verbose_name='留言')),
                ('description', models.CharField(max_length=125, null=True, verbose_name='描述')),
                ('totalCost', models.FloatField(default=0.0, verbose_name='总价')),
                ('netCost', models.FloatField(default=0.0, verbose_name='实付')),
                ('discount', models.FloatField(default=0.0, verbose_name='优惠')),
                ('shipping_fee', models.FloatField(default=0.0, verbose_name='邮费')),
                ('paymentInfo', models.JSONField(null=True, verbose_name='支付信息')),
                ('reviewState', models.JSONField(null=True, verbose_name='评论状态')),
                ('goodsList', models.JSONField(null=True, verbose_name='商品列表')),
                ('address', models.JSONField(null=True, verbose_name='邮寄地址')),
                ('payment_time', models.DateTimeField(null=True, verbose_name='支付时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': 'tb_order',
                'verbose_name_plural': 'tb_order',
                'db_table': 'tb_order',
                'ordering': ['-create_time'],
            },
        )
    ]
