# Generated by Django 3.1.1 on 2022-06-05 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
        ('customer', '0002_customer_store'),
        ('orders', '0001_initial'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='refundorder',
        #     name='store',
        #     field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='all_refundOrders', to='store.store', verbose_name='店铺订单'),
        # ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer', to_field='openid', verbose_name='顾客'),
        ),
        migrations.AddField(
            model_name='order',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_orders', to='store.store', verbose_name='店铺订单'),
        ),
    ]
