# Generated by Django 3.1.1 on 2022-02-01 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_auto_20211223_1848'),
        ('customer', '0002_auto_20220201_2141'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='customer.customer', verbose_name='顾客'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='all_orders', to='store.store', verbose_name='店铺订单'),
            preserve_default=False,
        ),
    ]
