# Generated by Django 3.1.1 on 2022-02-21 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20220221_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='amount',
            field=models.FloatField(default=0, verbose_name='总价'),
        ),
    ]
