# Generated by Django 3.1.1 on 2022-02-24 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20220221_1032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='amount',
            new_name='totalCost',
        ),
        migrations.AddField(
            model_name='order',
            name='note',
            field=models.CharField(max_length=250, null=True, verbose_name='留言'),
        ),
        migrations.AddField(
            model_name='order',
            name='paymentInfo',
            field=models.JSONField(null=True, verbose_name='支付信息'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_fee',
            field=models.FloatField(default=0.0, verbose_name='邮费'),
        ),
    ]
