# Generated by Django 3.1.1 on 2022-02-28 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20220224_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
    ]
