# Generated by Django 3.1.1 on 2022-03-01 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_update_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefundOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refundNum', models.CharField(max_length=20, unique=True, verbose_name='退款编号')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('orderNum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order', to_field='orderNum', verbose_name='订单号')),
            ],
            options={
                'verbose_name': 'tb_refund_order',
                'verbose_name_plural': 'tb_refund_order',
                'db_table': 'tb_refund_order',
            },
        ),
    ]
