# Generated by Django 3.1.1 on 2022-03-01 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_refundorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='addedReview',
            field=models.BooleanField(default=False, verbose_name='是否追评'),
        ),
    ]
