# Generated by Django 3.1.1 on 2022-03-05 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20220302_1911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='addedReview',
        ),
        migrations.AddField(
            model_name='order',
            name='reviewState',
            field=models.JSONField(null=True, verbose_name='评论状态'),
        ),
    ]
