# Generated by Django 3.1.1 on 2022-03-11 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_auto_20220305_1919'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-create_time'], 'verbose_name': 'tb_order', 'verbose_name_plural': 'tb_order'},
        ),
        migrations.AlterModelOptions(
            name='refundorder',
            options={'ordering': ['-create_time'], 'verbose_name': 'tb_refund_order', 'verbose_name_plural': 'tb_refund_order'},
        ),
        migrations.AddField(
            model_name='refundorder',
            name='refund_fee',
            field=models.FloatField(default=0, verbose_name='退款金额'),
        ),
        migrations.AddField(
            model_name='refundorder',
            name='status',
            field=models.CharField(max_length=10, null=True, verbose_name='退款状态'),
        ),
    ]
