# Generated by Django 3.1.1 on 2022-03-11 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0015_remove_customer_defaultaddress'),
        ('orders', '0012_auto_20220311_1244'),
    ]

    operations = [
        migrations.RenameField(
            model_name='refundorder',
            old_name='orderNum',
            new_name='order',
        ),
        migrations.AddField(
            model_name='refundorder',
            name='customer',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='refundList', to='customer.customer', to_field='openid', verbose_name='顾客'),
            preserve_default=False,
        ),
    ]
