# Generated by Django 3.1.1 on 2022-03-12 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_auto_20220311_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='refundorder',
            name='description',
            field=models.CharField(default='', max_length=200, verbose_name='退款详述'),
        ),
        migrations.AddField(
            model_name='refundorder',
            name='imgs',
            field=models.JSONField(null=True, verbose_name='附件'),
        ),
        migrations.AddField(
            model_name='refundorder',
            name='reason',
            field=models.CharField(default='', max_length=100, verbose_name='退款原因'),
        ),
        migrations.AddField(
            model_name='refundorder',
            name='refundType',
            field=models.IntegerField(default=1, verbose_name='退款类型'),
        ),
    ]
