# Generated by Django 3.1.1 on 2022-03-12 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_auto_20220312_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refundorder',
            name='refundNum',
            field=models.CharField(max_length=10, unique=True, verbose_name='退款编号'),
        ),
        migrations.AlterField(
            model_name='refundorder',
            name='refundType',
            field=models.CharField(max_length=20, verbose_name='退款类型'),
        ),
    ]
