# Generated by Django 3.1.1 on 2022-03-12 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_auto_20220312_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refundorder',
            name='status',
            field=models.CharField(default='处理中', max_length=10, verbose_name='退款状态'),
        ),
    ]
