# Generated by Django 3.1.1 on 2022-03-12 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_auto_20220312_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refundorder',
            name='refundNum',
            field=models.CharField(max_length=20, unique=True, verbose_name='退款编号'),
        ),
    ]
