# Generated by Django 3.1.1 on 2021-09-18 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('mobile', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='手机号')),
                ('name', models.CharField(max_length=20, null=True, verbose_name='姓名')),
                ('mail', models.CharField(max_length=30, null=True, verbose_name='邮箱')),
                ('wechat', models.CharField(max_length=50, null=True, unique=True, verbose_name='微信号')),
                ('pid', models.CharField(max_length=50, unique=True, verbose_name='用户id')),
                ('payment_time', models.DateTimeField(null=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'tb_users',
            },
        ),
    ]
