# Generated by Django 3.1.1 on 2022-06-05 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('mobile', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='手机号')),
                ('name', models.CharField(max_length=20, null=True, verbose_name='姓名')),
                ('mail', models.CharField(max_length=30, null=True, verbose_name='邮箱')),
                ('wechat', models.CharField(max_length=50, null=True, unique=True, verbose_name='微信号')),
                ('pid', models.CharField(max_length=50, unique=True, verbose_name='用户id')),
                ('token', models.CharField(max_length=250, null=True, verbose_name='token')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='注册时间')),
                ('store', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.store', verbose_name='默认店铺')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'tb_users',
            },
        ),
    ]
