# Generated by Django 3.1.1 on 2021-11-04 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='payment_time',
        ),
        migrations.AddField(
            model_name='user',
            name='token',
            field=models.CharField(max_length=250, null=True, verbose_name='token'),
        ),
    ]
