# Generated by Django 3.1.1 on 2021-11-04 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20211104_0830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pid',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='用户id'),
        ),
    ]
