# Generated by Django 3.1.1 on 2021-11-04 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_create_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pid',
            field=models.CharField(max_length=50, unique=True, verbose_name='用户id'),
        ),
    ]
