# Generated by Django 3.1.1 on 2021-11-05 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20211105_0921'),
        ('users', '0005_auto_20211104_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.store', verbose_name='默认店铺'),
        ),
    ]
