# Generated by Django 3.1.1 on 2022-06-05 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.JSONField(default=list, verbose_name='详情')),
                ('tabbar', models.JSONField(null=True, verbose_name='导航')),
                ('labels', models.JSONField(default=list, verbose_name='标签')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '详情',
                'verbose_name_plural': '详情',
                'db_table': 'tb_detail',
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appid', models.CharField(max_length=50, null=True, unique=True, verbose_name='微信号')),
                ('mch_id', models.CharField(max_length=15, null=True, unique=True, verbose_name='商户id')),
                ('product_name', models.CharField(max_length=20, verbose_name='产品名')),
                ('version', models.CharField(max_length=20, verbose_name='版本')),
                ('storename', models.CharField(max_length=40, verbose_name='店铺名称')),
                ('trademark', models.CharField(max_length=100, verbose_name='店铺标识')),
                ('address', models.JSONField(max_length=200, verbose_name='店铺地址')),
                ('industry', models.JSONField(max_length=100, verbose_name='行业')),
                ('introduce', models.CharField(max_length=250, null=True, verbose_name='店铺简介')),
                ('mobile', models.CharField(max_length=20, null=True, verbose_name='手机号')),
                ('telephone', models.CharField(max_length=20, null=True, verbose_name='办公电话')),
                ('name', models.CharField(max_length=20, null=True, verbose_name='联系人姓名')),
                ('mail', models.CharField(max_length=30, null=True, verbose_name='邮箱')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '店铺',
                'verbose_name_plural': '店铺',
                'db_table': 'tb_store',
                'ordering': ['-update_time', '-create_time'],
            },
        ),
    ]
