# Generated by Django 3.1.1 on 2021-09-18 03:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('areas', '__first__'),
        ('industry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storename', models.CharField(max_length=40, unique=True, verbose_name='店铺名称')),
                ('trademark', models.CharField(max_length=100, verbose_name='店铺标识')),
                ('introduce', models.CharField(max_length=250, null=True, verbose_name='店铺简介')),
                ('mobile', models.CharField(max_length=20, null=True, verbose_name='手机号')),
                ('name', models.CharField(max_length=20, null=True, verbose_name='姓名')),
                ('mail', models.CharField(max_length=30, null=True, verbose_name='邮箱')),
                ('wechat', models.CharField(max_length=50, null=True, unique=True, verbose_name='微信号')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('address', models.ForeignKey(db_column='address', on_delete=django.db.models.deletion.CASCADE, to='areas.area', verbose_name='店铺地址')),
                ('industry', models.ForeignKey(db_column='industry', on_delete=django.db.models.deletion.CASCADE, to='industry.industry', to_field='name', verbose_name='行业')),
                ('pid', models.ForeignKey(db_column='pid', on_delete=django.db.models.deletion.CASCADE, related_name='all_store', to=settings.AUTH_USER_MODEL, to_field='pid', verbose_name='用户')),
            ],
            options={
                'verbose_name': '店铺',
                'verbose_name_plural': '店铺',
                'db_table': 'tb_store',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, unique=True, verbose_name='名称')),
                ('status', models.CharField(max_length=10, verbose_name='页面状态')),
                ('remarks', models.CharField(max_length=100, null=True, verbose_name='备注')),
                ('marks', models.JSONField(null=True, verbose_name='标签')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_info', to='store.store', verbose_name='页面详情')),
            ],
            options={
                'verbose_name': '页面',
                'verbose_name_plural': '页面',
                'db_table': 'tb_pages',
            },
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.JSONField(verbose_name='详情')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_info', to='store.store', verbose_name='店铺详情')),
            ],
            options={
                'verbose_name': '详情',
                'verbose_name_plural': '详情',
                'db_table': 'tb_detail',
            },
        ),
    ]
