# Generated by Django 3.1.1 on 2021-09-18 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='address',
            field=models.JSONField(max_length=200, verbose_name='店铺地址'),
        ),
        migrations.AlterField(
            model_name='store',
            name='industry',
            field=models.JSONField(max_length=100, verbose_name='行业'),
        ),
    ]
