# Generated by Django 3.1.1 on 2021-09-18 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20210918_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='product_name',
            field=models.CharField(default=1, max_length=20, verbose_name='产品名'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='store',
            name='version',
            field=models.CharField(default=1, max_length=20, verbose_name='版本'),
            preserve_default=False,
        ),
    ]
