# Generated by Django 3.1.1 on 2021-09-21 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20210918_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='storename',
            field=models.CharField(max_length=40, verbose_name='店铺名称'),
        ),
    ]
