# Generated by Django 3.1.1 on 2021-10-14 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20210921_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='pages',
            field=models.JSONField(default=1, verbose_name='页面'),
            preserve_default=False,
        ),
    ]
