# Generated by Django 3.1.1 on 2021-11-02 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_detail_tabbar'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='telephone',
            field=models.CharField(max_length=20, null=True, verbose_name='办公电话'),
        ),
    ]
