# Generated by Django 3.1.1 on 2021-11-04 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_store_telephone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
