# Generated by Django 3.1.1 on 2021-12-23 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20211105_0921'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='store',
            options={'ordering': ['-update_time', '-create_time'], 'verbose_name': '店铺', 'verbose_name_plural': '店铺'},
        ),
    ]
