# Generated by Django 3.1.1 on 2022-02-06 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_auto_20211223_1848'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='wechat',
            new_name='appid',
        ),
        migrations.AddField(
            model_name='store',
            name='mch_id',
            field=models.CharField(max_length=15, null=True, unique=True, verbose_name='商户id'),
        ),
        migrations.AlterField(
            model_name='store',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
